pipeline {
    agent any
    stages{
        stage('SCM Checkout'){
            steps{
                git 'https://github.com/deeprony7/devops-practical-challenge'
            }
        }
        stage('Execute Ansible PB'){
            steps{
                ansiblePlaybook credentialsId: 'd5c7bf35-d4ba-4914-ad35-24d8be8bf114', disableHostKeyChecking: true, installation: 'ansible', inventory: 'With-Playbook/inv.ini', playbook: 'With-Playbook/nginx_install.yml'
            }
        }
    }
}