pipeline {
    agent any
    stages{
        stage('SCM Checkout'){
            steps{
                git 'https://github.com/deeprony7/devops-practical-challenge'
            }
        }
        stage('Execute Ansible PB'){
            steps{
                ansiblePlaybook become: true, credentialsId: '7022a5e7-e749-4d17-9883-a159e506be65', disableHostKeyChecking: true, installation: 'ansible', inventory: 'With-Playbook/inv.ini', playbook: 'With-Playbook/nginx_install.yml'
            }
        }
    }
}